In [11]:
import pandas as pd
import numpy as np

In [15]:
df = pd.DataFrame({
    "EmployeeID": [101.0, 102.0, 103.0, 104.0, 105.0, 106.0],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Age": [25, 30, 40, 40, 29, 40],
    "Salary": [50000.0, 45000.0, 60000.0, np.nan, 48000.0, 70000.0],
    "Experience": [2.0, 5.0, 4.0, 10.0, np.nan, 7.0]
})
df

   EmployeeID     Name Department  Age   Salary  Experience
0       101.0    Alice         IT   25  50000.0         2.0
1       102.0      Bob         HR   30  45000.0         5.0
2       103.0  Charlie         IT   40  60000.0         4.0
3       104.0    David    Finance   40      NaN        10.0
4       105.0      Eva         HR   29  48000.0         NaN
5       106.0    Frank         IT   40  70000.0         7.0

In [17]:
Manager = pd.DataFrame({
    "Department": ["IT", "HR", "Finance"],
    "Manager": ["A", "B", "C"]
})
Manager

  Department Manager
0         IT       A
1         HR       B
2    Finance       C

In [18]:
# Merge Both Data on Department (Add Columns)
Merge_data = pd.merge(df, Manager, on='Department')
Merge_data

   EmployeeID     Name Department  Age   Salary  Experience Manager
0       101.0    Alice         IT   25  50000.0         2.0       A
1       102.0      Bob         HR   30  45000.0         5.0       B
2       103.0  Charlie         IT   40  60000.0         4.0       A
3       104.0    David    Finance   40      NaN        10.0       C
4       105.0      Eva         HR   29  48000.0         NaN       B
5       106.0    Frank         IT   40  70000.0         7.0       A

In [34]:
# Merge Both Data on Same (Add Columns and Row Cross)
Merge_data_same = pd.merge(df, df, on='Department')
Merge_data_same

,EmployeeID_x,Name_x,Department,Age_x,Salary_x,Experience_x,EmployeeID_y,Name_y,Age_y,Salary_y,Experience_y
0,101.0,Alice,IT,25,50000.0,2.0,101.0,Alice,25,50000.0,2.0
1,101.0,Alice,IT,25,50000.0,2.0,103.0,Charlie,40,60000.0,4.0
2,101.0,Alice,IT,25,50000.0,2.0,106.0,Frank,40,70000.0,7.0
3,102.0,Bob,HR,30,45000.0,5.0,102.0,Bob,30,45000.0,5.0
4,102.0,Bob,HR,30,45000.0,5.0,105.0,Eva,29,48000.0,NaN
5,103.0,Charlie,IT,40,60000.0,4.0,101.0,Alice,25,50000.0,2.0
6,103.0,Charlie,IT,40,60000.0,4.0,103.0,Charlie,40,60000.0,4.0
7,103.0,Charlie,IT,40,60000.0,4.0,106.0,Frank,40,70000.0,7.0
8,104.0,David,Finance,40,NaN,10.0,104.0,David,40,NaN,10.0
9,105.0,Eva,HR,29,48000.0,NaN,102.0,Bob,30,45000.0,5.0
10,105.0,Eva,HR,29,48000.0,NaN,105.0,Eva,29,48000.0,NaN
11,106.0,Frank,IT,40,70000.0,7.0,101.0,Alice,25,50000.0,2.0
12,106.0,Frank,IT,40,70000.0,7.0,103.0,Charlie,40,60000.0,4.0
13,106.0,Frank,IT,40,70000.0,7.0,106.0,Frank,40,70000.0,7.0

In [33]:
# Concate Data (Add Rows)
Concat_data = pd.concat([df, df])
Concat_data

   EmployeeID     Name Department  Age   Salary  Experience
0       101.0    Alice         IT   25  50000.0         2.0
1       102.0      Bob         HR   30  45000.0         5.0
2       103.0  Charlie         IT   40  60000.0         4.0
3       104.0    David    Finance   40      NaN        10.0
4       105.0      Eva         HR   29  48000.0         NaN
5       106.0    Frank         IT   40  70000.0         7.0
0       101.0    Alice         IT   25  50000.0         2.0
1       102.0      Bob         HR   30  45000.0         5.0
2       103.0  Charlie         IT   40  60000.0         4.0
3       104.0    David    Finance   40      NaN        10.0
4       105.0      Eva         HR   29  48000.0         NaN
5       106.0    Frank         IT   40  70000.0         7.0

In [39]:
# Concate Data on Diffrent Data shape(Add Rows)
Concat_data = pd.concat([df, Manager])
Concat_data

   EmployeeID     Name Department   Age   Salary  Experience Manager
0       101.0    Alice         IT  25.0  50000.0         2.0     NaN
1       102.0      Bob         HR  30.0  45000.0         5.0     NaN
2       103.0  Charlie         IT  40.0  60000.0         4.0     NaN
3       104.0    David    Finance  40.0      NaN        10.0     NaN
4       105.0      Eva         HR  29.0  48000.0         NaN     NaN
5       106.0    Frank         IT  40.0  70000.0         7.0     NaN
0         NaN      NaN         IT   NaN      NaN         NaN       A
1         NaN      NaN         HR   NaN      NaN         NaN       B
2         NaN      NaN    Finance   NaN      NaN         NaN       C