In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
df = data.copy()
df.head(2)

   R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [6]:
df['Profit'] = df['Profit'].fillna(df['Profit'].mean()) 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [18]:
print(df.duplicated())
print("Sum Of All Duplicated Values :\t", df.duplicated().sum())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
dtype: bool
Sum Of All Duplicated Values :	 0

In [27]:
print(df['State'].duplicated())
# print(df.duplicated(subset=['State'])) # Both Same

print("Sum Of All Duplicated Values :\t", df['State'].duplicated().sum())

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23     True
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
38     True
39     True
40     True
41     True
42     True
43     True
44     True
45     True
46     True
47     True
48     True
49     True
dtype: bool
Sum Of All Duplicated Values :	 47

In [20]:
df['Profit'].duplicated().sum()

5

In [25]:
# To see only duplicated Data all Values
Duplicate_data = df[df['Profit'].duplicated()]
Duplicate_data

    R&D Spend  Administration  Marketing Spend       State         Profit
22   73994.56       122782.75        303319.26     Florida  112466.881364
23   67532.53       105751.03        304768.73     Florida  112466.881364
24   77044.01        99281.34        140574.81    New York  112466.881364
25   64664.71       139553.16        137962.62  California  112466.881364
26   75328.87       144135.98        134050.07     Florida  112466.881364

In [ ]:
# To Remove Duplicate
df.drop_duplicates()