In [1]:
import pandas as pd
import numpy as np

data = {
    "EmployeeID": [101, 102, 103, 104, 105, 106],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Age": [25.0, 30.0, np.nan, 40.0, 29.0, np.nan],
    "Salary": [50000.0, 45000.0, 60000.0, np.nan, 48000.0, 70000.0],
    "Experience": [2.0, 5.0, 4.0, 10.0, np.nan, 7.0]
}

df = pd.DataFrame(data)
print(df)

   EmployeeID     Name Department   Age   Salary  Experience
0         101    Alice         IT  25.0  50000.0         2.0
1         102      Bob         HR  30.0  45000.0         5.0
2         103  Charlie         IT   NaN  60000.0         4.0
3         104    David    Finance  40.0      NaN        10.0
4         105      Eva         HR  29.0  48000.0         NaN
5         106    Frank         IT   NaN  70000.0         7.0

In [2]:
df["Join Date"] = pd.to_datetime(["2021-01-01", "2020-05-03", "2019-08-10", "2022-02-01", "2021-07-15", "2018-06-20"])
df

   EmployeeID     Name Department   Age   Salary  Experience  Join Date
0         101    Alice         IT  25.0  50000.0         2.0 2021-01-01
1         102      Bob         HR  30.0  45000.0         5.0 2020-05-03
2         103  Charlie         IT   NaN  60000.0         4.0 2019-08-10
3         104    David    Finance  40.0      NaN        10.0 2022-02-01
4         105      Eva         HR  29.0  48000.0         NaN 2021-07-15
5         106    Frank         IT   NaN  70000.0         7.0 2018-06-20

In [3]:
a = df.set_index(df["Join Date"])
a.sort_index(inplace = True)
a

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date
Join Date,,,,,,,
2018-06-20,106,Frank,IT,NaN,70000.0,7.0,2018-06-20
2019-08-10,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10
2020-05-03,102,Bob,HR,30.0,45000.0,5.0,2020-05-03
2021-01-01,101,Alice,IT,25.0,50000.0,2.0,2021-01-01
2021-07-15,105,Eva,HR,29.0,48000.0,NaN,2021-07-15
2022-02-01,104,David,Finance,40.0,NaN,10.0,2022-02-01

In [4]:
# Date Time Year 
df["Year"] = df["Join Date"].dt.year
df

   EmployeeID     Name Department   Age   Salary  Experience  Join Date  Year
0         101    Alice         IT  25.0  50000.0         2.0 2021-01-01  2021
1         102      Bob         HR  30.0  45000.0         5.0 2020-05-03  2020
2         103  Charlie         IT   NaN  60000.0         4.0 2019-08-10  2019
3         104    David    Finance  40.0      NaN        10.0 2022-02-01  2022
4         105      Eva         HR  29.0  48000.0         NaN 2021-07-15  2021
5         106    Frank         IT   NaN  70000.0         7.0 2018-06-20  2018

In [5]:
# Date Time Month
df["Month"] = df["Join Date"].dt.month
df

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month
0,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1
1,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5
2,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8
3,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2
4,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7
5,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6

In [6]:
# Date Time Day
df["Day"] = df["Join Date"].dt.day
df

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month,Day
0,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1,1
1,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5,3
2,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8,10
3,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2,1
4,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7,15
5,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6,20

In [7]:
# Date Time Current Date Time
df["Current Date Time"] = pd.to_datetime("now")
df

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month,Day,Current Date Time
0,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1,1,2026-01-25 17:20:05.788092
1,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5,3,2026-01-25 17:20:05.788092
2,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8,10,2026-01-25 17:20:05.788092
3,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2,1,2026-01-25 17:20:05.788092
4,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7,15,2026-01-25 17:20:05.788092
5,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6,20,2026-01-25 17:20:05.788092

In [8]:
# Current Date Time Day
df["Hour"] = df["Current Date Time"].dt.hour
df

# Current Date Time Day
df["Minites"] = df["Current Date Time"].dt.minute
df

# Current Date Time Day
df["Seconds"] = df["Current Date Time"].dt.second
df

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month,Day,Current Date Time,Hour,Minites,Seconds
0,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1,1,2026-01-25 17:20:05.788092,17,20,5
1,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5,3,2026-01-25 17:20:05.788092,17,20,5
2,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8,10,2026-01-25 17:20:05.788092,17,20,5
3,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2,1,2026-01-25 17:20:05.788092,17,20,5
4,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7,15,2026-01-25 17:20:05.788092,17,20,5
5,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6,20,2026-01-25 17:20:05.788092,17,20,5

In [9]:
# Date Time Current Date Time 
df["Current Date Time 1"] = pd.Timestamp.now()
df

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month,Day,Current Date Time,Hour,Minites,Seconds,Current Date Time 1
0,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1,1,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
1,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5,3,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8,10,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
3,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2,1,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
4,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7,15,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
5,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6,20,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255

In [10]:
# Set Current Date Time As Index 
df.set_index(df["Current Date Time 1"])
# df.sort_index()

,EmployeeID,Name,Department,Age,Salary,Experience,Join Date,Year,Month,Day,Current Date Time,Hour,Minites,Seconds,Current Date Time 1
Current Date Time 1,,,,,,,,,,,,,,,
2026-01-25 17:20:05.841255,101,Alice,IT,25.0,50000.0,2.0,2021-01-01,2021,1,1,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2026-01-25 17:20:05.841255,102,Bob,HR,30.0,45000.0,5.0,2020-05-03,2020,5,3,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2026-01-25 17:20:05.841255,103,Charlie,IT,NaN,60000.0,4.0,2019-08-10,2019,8,10,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2026-01-25 17:20:05.841255,104,David,Finance,40.0,NaN,10.0,2022-02-01,2022,2,1,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2026-01-25 17:20:05.841255,105,Eva,HR,29.0,48000.0,NaN,2021-07-15,2021,7,15,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255
2026-01-25 17:20:05.841255,106,Frank,IT,NaN,70000.0,7.0,2018-06-20,2018,6,20,2026-01-25 17:20:05.788092,17,20,5,2026-01-25 17:20:05.841255

In [ ]:
df.to_csv()