In [1]:
import pandas as pd
data = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
df = data.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           44 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

# Sorting

In [2]:
# Sort Profit
Sorted_Profit = df.sort_values("Profit")  # Default Ascending is True
Sorted_Profit.head(3)

    R&D Spend  Administration  Marketing Spend       State    Profit
49       0.00       116983.80         45173.06  California  14681.40
48     542.05        51743.15             0.00    New York  35673.41
47       0.00       135426.92             0.00  California  42559.73

In [3]:
# Sort Profit Decending
Desc_Profit = df.sort_values('Profit', ascending = False)
Desc_Profit.head(3)

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [4]:
# Sort Descending Order in Original Data

# df.sort_values('Profit', ascending = False, inplace = True)  # inplace = True

# Indexing

In [5]:
# Set Marketing Spend as Index
Marketing_Spend_Indexed = df.set_index('Marketing Spend')
Marketing_Spend_Indexed.head(3)

                 R&D Spend  Administration       State     Profit
Marketing Spend
471784.10        165349.20       136897.80    New York  192261.83
443898.53        162597.70       151377.59  California  191792.06
407934.54        153441.51       101145.55     Florida  191050.39

In [7]:
# Set Marketing Spend as Index Parmanently on Data

# MarSpend_Index_Desc = df.set_index('Marketing Spend', inplace = True)
MarSpend_Index_Desc.head(3)

In [29]:
# To Revoke The Changes of Indexing
df.reset_index(inplace = True)

In [9]:
# Set Marketing Spend as Index
State_Indexed = df.set_index('State')
State_Indexed.head(3)

            R&D Spend  Administration  Marketing Spend     Profit
State
New York    165349.20       136897.80        471784.10  192261.83
California  162597.70       151377.59        443898.53  191792.06
Florida     153441.51       101145.55        407934.54  191050.39