In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# Column Selection

In [3]:
# Column Selection 1D
one_dimension = df["R&D Spend"]

# Columns Selection 2D
two_dimension = df[['Marketing Spend', 'State']]

# Filtering

In [4]:
# Filter Data Where Marketing Spend Greater Then 4 lakhs 
df[df["Marketing Spend"] > 400000]

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [29]:
# Filter Data Where Marketing Spend Greater Profit 
df[df["Marketing Spend"] > df["Profit"]*3]

    R&D Spend  Administration  Marketing Spend       State     Profit
27   72107.60       127864.55        353183.81    New York  105008.31
46    1315.46       115816.21        297114.46     Florida   49490.75
49       0.00       116983.80         45173.06  California   14681.40

In [35]:
# Filtering More Then Two Conditions (Profit Double then Marketing) & (State = New York)
df[(df['Profit'] > df['Marketing Spend'] * 2) & (df['State'] == 'New York')]

    R&D Spend  Administration  Marketing Spend     State     Profit
19   86419.70       153514.11             0.00  New York  122776.86
45    1000.23       124153.04          1903.93  New York   64926.08
48     542.05        51743.15             0.00  New York   35673.41

In [36]:
# Get Specific Values by Row Number
df.loc[1]

R&D Spend            162597.7
Administration      151377.59
Marketing Spend     443898.53
State              California
Profit              191792.06
Name: 1, dtype: object

In [37]:
# Get Specific Range of Values by Row Number
df.loc[1:5]

   R&D Spend  Administration  Marketing Spend       State     Profit
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12

In [40]:
# Get Specific Range of Values by Row Number and Range of Coloumns
df.loc[1:5, "Administration":"State"]

   Administration  Marketing Spend       State
1       151377.59        443898.53  California
2       101145.55        407934.54     Florida
3       118671.85        383199.62    New York
4        91391.77        366168.42     Florida
5        99814.71        362861.36    New York

In [11]:
# Integer-based indexing(iloc) Get iloc for [row_no, coloumns_no] = [:, :-1] and loc for ['row_name', 'column_name'] = ['state']
df.iloc[5:11, :]

    R&D Spend  Administration  Marketing Spend       State     Profit
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95

In [13]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [14]:
df.iloc[1, 2]

443898.53

In [15]:
df.loc[1, 2]

KeyError: 2