In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"E:\DATA FOR TEST\50 Startups\50_Startups.csv")
data.head(2)

   R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           44 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [5]:
# Convert Float Value to Interger 
data['Profit'] = data['Profit'].astype('int')

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [6]:
#  Canont Convert Null Values Columns Data Type
data['Profit'] = data['Profit'].fillna(data['Profit'].mean())


# Same Code Above

# Convert Float Value to Interger 
data['Profit'] = data['Profit'].astype('int')

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     int32
dtypes: float64(3), int32(1), object(1)
memory usage: 1.9+ KB

In [12]:
# Again Convert integer to float
data['Profit'] = data['Profit'].astype('float')
print(data.info())
data.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB
None

   R&D Spend  Administration  Marketing Spend       State    Profit
0   165349.2       136897.80        471784.10    New York  192261.0
1   162597.7       151377.59        443898.53  California  191792.0

In [4]:
# Due to Changes After Point Values Are Disabel so we use Round
data['Profit'] = data['Profit'].round(2)
data.head(2)

   R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.2       136897.80        471784.10    New York  192261.83
1   162597.7       151377.59        443898.53  California  191792.06

In [13]:
# Convert State to Category
data['State'] = data['State'].astype('category')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     category
 4   Profit           50 non-null     float64
dtypes: category(1), float64(4)
memory usage: 1.9 KB

In [14]:
# Convert State to Object
data['State'] = data['State'].astype('object')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB

In [15]:
# Convert Profit to Object
data['Profit'] = data['Profit'].astype('object')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     object
dtypes: float64(3), object(2)
memory usage: 2.1+ KB

In [16]:
# Convert Profit to Object
data['Profit'] = data['Profit'].astype('float64')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB